language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sean' ]; then cd .. && eval "mv $currentfolder generator-sean" && cd generator-sean; fi

